In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

current_dir = os.path.abspath(os.path.curdir)
project_home = os.path.dirname(current_dir)
print('Working out of:',current_dir)

Working out of: /Users/catcamacho/Library/CloudStorage/Box-Box/CCP/HBN_study/social_functioning/analysis_notebooks

### Indexing a pandas dataframe

to index by label, use ".loc"

* for example: `assq.loc[:,['ASSQ_19', 'ASSQ_20', 'ASSQ_21']]`

to index by index(number) use ".iloc"

* for example: `assq.iloc[:,2:9]`

In [2]:
#combine CELF data together across ages
celf_full_9to21 = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_CELF_Full_9to21_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['CELF_USP_P','CELF_RLI_P','CELF_ELI_P']]
celf_full_5to8 = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_CELF_Full_5to8_20210322.csv'), 
                             header=0, skiprows=[1], index_col='EID').loc[:,['CELF_USP_P', 'CELF_RLI_P','CELF_ELI_P']]
celf = pd.concat([celf_full_5to8,celf_full_9to21])

In [3]:
# combine CBCL across ages
cbcl = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_CBCL_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['CBCL_01', 'CBCL_19', 'CBCL_11', 'CBCL_21', 'CBCL_28', 'CBCL_25', 
                                                                   'CBCL_27', 'CBCL_37', 'CBCL_88', 'CBCL_109', 'CBCL_111']]

cbcl_pre = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_CBCL_PRE_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['CBCL_Pre_02', 'CBCL_Pre_96', 'CBCL_Pre_10', 'CBCL_Pre_18',
                                                                   'CBCL_Pre_20', 'CBCL_Pre_25', 'CBCL_Pre_30', 'CBCL_Pre_35', 
                                                                   'CBCL_Pre_83', 'CBCL_Pre_97', 'CBCL_Pre_98']]
cbcl_pre.columns = cbcl.columns
cbcl = pd.concat([cbcl, cbcl_pre])

In [4]:
# combine SRS across ages
srs = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_SRS_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:75]
srs.drop(['SRS_10','SRS_32'], axis=1)
srs_pre = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_SRS_PRE_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:75]
srs_pre.drop(['SRS_Pre_10','SRS_Pre_32'], axis=1)

srs_pre.columns = srs.columns
srs = pd.concat([srs, srs_pre])

In [5]:
# Load questionnaire data
ysr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_YSR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:129]
icu_p = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_ICU_P_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:, 10:34]
ace = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_ACE_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['ACE_04', 'ACE_05', 'ACE_06', 'ACE_07']]
mfq_p = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_MFQ_P_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['MFQ_P_05', 'MFQ_P_11','MFQ_P_12', 'MFQ_P_13',
                                                                   'MFQ_P_14', 'MFQ_P_18','MFQ_P_20', 'MFQ_P_28', 'MFQ_P_29','MFQ_P_30', 'MFQ_P_34']]
scared_p = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_SCARED_P_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['SCARED_P_03', 'SCARED_P_05', 'SCARED_P_08', 'SCARED_P_09', 
                                                                   'SCARED_P_10', 'SCARED_P_26', 'SCARED_P_32', 'SCARED_P_36', 'SCARED_P_39', 'SCARED_P_40']]
assq = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_ASSQ_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['ASSQ_06', 'ASSQ_11', 'ASSQ_12', 'ASSQ_13', 'ASSQ_14', 'ASSQ_15', 'ASSQ_16', 'ASSQ_17', 
                                                                   'ASSQ_19', 'ASSQ_25']]
cis_p = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_CIS_P_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['CIS_P_02', 'CIS_P_03', 'CIS_P_05','CIS_P_07', 'CIS_P_09', 'CIS_P_10']]
mfq_sr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_MFQ_SR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['MFQ_SR_18', 'MFQ_SR_20', 'MFQ_SR_28','MFQ_SR_30']]
scared_sr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_SCARED_SR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['SCARED_SR_3', 'SCARED_SR_5', 'SCARED_SR_8','SCARED_SR_10', 'SCARED_SR_14',
                                                                   'SCARED_SR_16','SCARED_SR_17', 'SCARED_SR_26', 'SCARED_SR_28','SCARED_SR_29', 
                                                                   'SCARED_SR_31', 'SCARED_SR_32','SCARED_SR_39','SCARED_SR_40']]
c3sr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_C3SR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['C3SR_08', 'C3SR_10', 'C3SR_11','C3SR_21', 'C3SR_22', 'C3SR_26',
                                                                   'C3SR_32', 'C3SR_34', 'C3SR_37','C3SR_39']]
ari_s = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_ARI_S_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['ARI_S_01']]
cis_sr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_CIS_SR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['CIS_SR_02', 'CIS_SR_03', 'CIS_SR_05','CIS_SR_07', 'CIS_SR_09','CIS_SR_10']]
whodas_sr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_WHODAS_SR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['WHODAS_SR_10', 'WHODAS_SR_11']]
icu_sr = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_ICU_SR_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['ICU_06', 'ICU_08', 'ICU_12','ICU_17', 'ICU_21','ICU_22']]
icu_sr.columns = ['ICU_SR_06', 'ICU_SR_08', 'ICU_SR_12','ICU_SR_17', 'ICU_SR_21','ICU_SR_22']
iat = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_IAT_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['IAT_03', 'IAT_13', 'IAT_19']]
phenx_school = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_PhenX_SchoolRisk_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['PhenX_School_07', 'PhenX_School_08']]

# add in missing questionnaires
eswan = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_ESWAN_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:81]
eswan.drop(['Panic_A01A','Panic_A01B','Panic_A02A','Panic_A02B','Panic_A03A','Panic_A03B',
            'Panic_B01','Panic_B02','Panic_B03','Panic_B04','Panic_B05','Panic_B06',
            'Panic_B07','Panic_B08','Panic_B09','Panic_B10','Panic_B11','Panic_B12','Panic_B13'], axis=1)
swan = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_SWAN_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:28]
scq = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_scq_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:50]
sas = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_sas_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').iloc[:,10:20]
sdq = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_SDQ_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['SDQ_01', 'SDQ_04', 'SDQ_06', 'SDQ_09', 'SDQ_11', 'SDQ_12',
                                                                   'SDQ_14', 'SDQ_17', 'SDQ_19', 'SDQ_20', 'SDQ_23', 'SDQ_26', 'SDQ_29_b']]
vineland = pd.read_csv(os.path.join(project_home, 'questionnaire_data', '9994_Vineland_20210322.csv'), 
                   header=0, skiprows=[1], index_col='EID').loc[:,['VL_Comm1_Scale', 'VL_Comm2_Scale', 'VL_Comm3_Scale', 'VL_DLS1_Scale', 
                                                                   'VL_DLS2_Scale', 'VL_DLS3_Scale', 'VL_Social1_Scale', 'VL_Social2_Scale', 'VL_Social3_Scale']]

In [6]:
# add in new questionnaire objects to the list below
qs = [celf, ysr, icu_p, ace, mfq_p, scared_p, assq, cis_p, mfq_sr, scared_sr, c3sr, srs,
      ari_s, cis_sr, whodas_sr, icu_sr, iat, phenx_school, eswan, swan, scq, sas, sdq, vineland, cbcl]

for i, q in enumerate(qs):
    q = q.drop_duplicates()
    if i==0:
        data = q
    else:
        data = data.merge(q, how='outer', left_index=True, right_index=True)
        
data = data.drop_duplicates()
data.to_csv(os.path.join(project_home, 'questionnaire_data','combined_data.csv'))
data.describe().to_csv(os.path.join(project_home, 'questionnaire_data','data_descriptions.csv'))
data.describe()

,CELF_USP_P,CELF_RLI_P,CELF_ELI_P,YSR_01,YSR_02,YSR_03,YSR_04,YSR_05,YSR_06,YSR_07,...,CBCL_19,CBCL_11,CBCL_21,CBCL_28,CBCL_25,CBCL_27,CBCL_37,CBCL_88,CBCL_109,CBCL_111
count,235.000000,236.000000,233.000000,1254.000000,1253.000000,1253.000000,1253.000000,1252.000000,1253.000000,1251.000000,...,1767.000000,1767.000000,1768.000000,1763.000000,1762.000000,1768.000000,1768.000000,1765.000000,1757.000000,1768.000000
mean,23.864255,30.712712,25.851073,0.507177,0.096568,1.021548,0.792498,0.452875,1.740623,0.497202,...,1.073571,0.724958,0.446267,0.929665,0.532350,0.785068,0.295814,0.613598,0.830393,0.397624
std,24.213234,27.336782,23.560193,0.598905,0.345342,0.648430,0.643255,0.673953,0.520124,0.611058,...,0.776362,0.725810,0.629808,0.720732,0.606915,0.758400,0.562097,0.708898,0.778212,0.597803
min,0.100000,0.100000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.000000,8.750000,9.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,16.000000,21.000000,19.000000,0.000000,0.000000,1.000000,1.000000,0.000000,2.000000,0.000000,...,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,37.000000,50.000000,32.000000,1.000000,0.000000,1.000000,1.000000,1.000000,2.000000,1.000000,...,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
max,98.000000,99.000000,97.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

## Pre-process data for EFA

In [ ]:
# identify items with at least 1000 subjects for imputation
descr = data.describe().T
min1000 = descr[descr['count']>=1000]
min1000 = min1000.index.to_list()

In [ ]:
# rescale each question to 0-1
preprocdata = data.loc[:, min1000]
preprocdata.loc[:,:] = MinMaxScaler().fit_transform(preprocdata.to_numpy())

# reverse code specific items
itemlabels = pd.read_excel(os.path.join(project_home, 'questionnaire_data', 'EFA_NewItemLabels.xlsx'))
# -- change "higher" to lower if needed
items_to_recode = itemlabels.loc[items_to_recode['Scale']=='higher', 'Original label'].to_list()
for item in items_to_recode:
    preprocdata[item] = 1 - preprocdata[item]
    
preprocdata.columns = itemlabels['New label'].to_list()

In [8]:
# impute missing values
preprocdata.loc[:,:] = IterativeImputer().fit_transform(preprocdata.to_numpy())
preprocdata.describe()

,YSR_01,YSR_02,YSR_03,YSR_04,YSR_05,YSR_06,YSR_07,YSR_08,YSR_09,YSR_10,...,CBCL_19,CBCL_11,CBCL_21,CBCL_28,CBCL_25,CBCL_27,CBCL_37,CBCL_88,CBCL_109,CBCL_111
count,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,...,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000,3533.000000
mean,0.273381,0.031711,0.513236,0.390673,0.206438,0.863946,0.261665,0.607734,0.447270,0.508901,...,0.458896,0.317190,0.168683,0.379757,0.204369,0.327918,0.102613,0.252347,0.346187,0.168364
std,0.225875,0.123153,0.225727,0.227545,0.240955,0.178412,0.213023,0.247848,0.270462,0.277991,...,0.345225,0.316202,0.275731,0.326872,0.260060,0.332136,0.237136,0.312471,0.337619,0.255048
min,-0.472594,-0.316544,0.000000,-0.342457,-0.615049,0.000000,-0.319238,-0.086011,-0.286560,-0.308848,...,-0.596361,-0.883684,-0.890264,-0.711131,-0.522940,-0.864234,-0.638627,-1.155945,-0.875141,-0.583113
25%,0.058494,0.000000,0.433193,0.279926,0.000000,0.802018,0.088773,0.500000,0.305656,0.383532,...,0.216732,0.000000,0.000000,0.096436,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.270403,0.000000,0.500000,0.414497,0.163972,0.898676,0.253267,0.578712,0.461835,0.500000,...,0.500000,0.293919,0.053920,0.412039,0.127381,0.319809,0.000000,0.181668,0.346187,0.047931
75%,0.463403,0.052479,0.592662,0.500000,0.325736,1.000000,0.410702,0.750501,0.550629,0.640324,...,0.629248,0.500000,0.332763,0.500000,0.500000,0.500000,0.139657,0.500000,0.500000,0.319725
max,1.006919,1.000000,1.145024,1.000000,1.000000,1.238663,1.000000,1.284217,1.080795,1.672720,...,1.490025,1.350019,1.083072,1.412565,1.006975,1.481910,1.101056,1.401429,1.170702,1.110694

In [9]:
# save preprocessed data
preprocdata.to_csv(os.path.join(project_home, 'questionnaire_data','preproc_min1000_socdata.csv'))